(use-modules (ice-9 streams))

(define (stream-ref s n)
  (if (= n 0)
    (stream-car s)
    (stream-ref (stream-cdr s) (- n 1))))
(define (stream-display s)
  (stream-for-each display-line s))
(define (display-line x)
  (display x)
  (newline))
(define (stream-enumerate-interval low high)
  (make-stream (lambda (state)
                 (if (> state high)
                   '()
                   (cons state
                         (+ state 1))))
               low))
(define (stream-filter pred stream)
  (make-stream (lambda (state)
                 (if (stream-null? state)
                   '()
                   (if (pred (stream-car state))
                     (cons (stream-car state) (stream-cdr state))
                     (if (stream-null? (stream-cdr state))
                       '()
                       (cons (stream-car (stream-cdr state))
                             (stream-cdr (stream-cdr state)))))))
               stream))
(define (integers-starting-from n)
  (make-stream (lambda (state) (cons state (+ state 1)))
               n))
(define integers (integers-starting-from 1))
(define (divisible? x y) (= (remainder x y) 0))
(define no-sevens
  (stream-filter (lambda (x) (not (divisible? x 7)))
                 integers))
(define (fibgen a b)
  (make-stream (lambda (state)
                 (cons (car state)
                       (cons (cdr state)
                             (+ (car state)
                                (cdr state)))))
               (cons a b)))
(define fibs (fibgen 0 1))
(define (sieve stream)
  (make-stream (lambda (state)
                 (cons (stream-car state)
                       (stream-filter
                         (lambda (x)
                           (not (divisible? x (stream-car state))))
                         (stream-cdr state))))
               stream))
(define primes (sieve (integers-starting-from 2)))
(define (xes x)
  (make-stream (lambda (state)
                 (cons state
                       state))
               x))
(define ones
  (xes 1))
(define (add-stream s1 s2)
  (stream-map + s1 s2))
(define (scale-stream stream factor)
  (stream-map (lambda (x) (* x factor)) stream))
(define (xble x)
  (make-stream (lambda (state)
                 (cons state
                       (* x state)))
               1))
(define double (xble 2))
(define factorials
  (make-stream (lambda (state)
                 (cons (cdr state)
                       (cons (+ (car state) 1)
                             (* (+ (car state) 1)
                                (cdr state)))))
               (cons 1 1)))
(define (partial-sums stream)
  (make-stream (lambda (state)
                 (cons (cdr state)
                       (cons (stream-cdr (car state))
                             (+ (stream-car (car state))
                                (cdr state)))))
               (cons (stream-cdr stream) (stream-car stream))))
