;; interval represents resistor
(define (make-interval a b) (cons a b))

(define (upper-bound x) (cdr x))

(define (lower-bound x) (car x))

;; give 0 + sign
(define (mul-interval x y)
  (let ((lx (lower-bound x))
        (ux (upper-bound x))
        (ly (lower-bound y))
        (uy (upper-bound y)))
    (cond ((< ux 0)
           ;; (-3 -2)
           (cond ((< uy 0)
                  ;; (-7 -5)
                  (make-interval (* ux uy) (* lx ly)))
                 ((> ly 0)
                  ;; (5 7)
                  (make-interval (* lx uy) (* ux ly)))
                 (else
                   ;; (-5 7)
                   (make-interval (* lx uy) (* lx ly)))))
          ((> lx 0)
           ;; (2 3)
           (cond ((< uy 0)
                  ;; (-7 -5)
                  (make-interval (* ux ly) (* lx uy)))
                 ((> ly 0)
                  ;; (5 7)
                  (make-interval (* lx ly) (* ux uy)))
                 (else
                   ;; (-5 7)
                   (make-interval (* ux ly) (* ux uy)))))
          (else
            ;; (-2 3)
            (cond ((< uy 0)
                   ;; (-7 -5)
                   (make-interval (* ux ly) (* lx ly)))
                  ((> ly 0)
                   ;; (5 7)
                   (make-interval (* lx uy) (* ux uy)))
                  (else
                    ;; (-5 7)
                    (let ((l (min (* lx uy) (* ux ly)))
                          (u (max (* lx ly) (* ux uy))))
                      (make-interval l u))))))))

(eq? (mul-interval (make-interval -3 -2) (make-interval -7 -5))
     (make-interval (* -2 -5) (* -3 -7)))
(eq? (mul-interval (make-interval -3 -2) (make-interval 5 7))
     (make-interval (* -3 7) (* -2 5)))
(eq? (mul-interval (make-interval -3 -2) (make-interval -5 7))
     (make-interval (* -3 7) (* -3 -5)))
(eq? (mul-interval (make-interval 2 3) (make-interval -7 -5))
     (make-interval (* 3 -7) (* 2 -5)))
(eq? (mul-interval (make-interval 2 3) (make-interval 5 7))
     (make-interval (* 2 5) (* 3 7)))
(eq? (mul-interval (make-interval 2 3) (make-interval -5 7))
     (make-interval (* 3 -5) (* 3 7)))
(eq? (mul-interval (make-interval -2 3) (make-interval -7 -5))
     (make-interval (* 3 -7) (* -2 -7)))
(eq? (mul-interval (make-interval -2 3) (make-interval 5 7))
     (make-interval (* -2 7) (* 3 7)))
(eq? (mul-interval (make-interval -2 3) (make-interval -5 7))
     (make-interval (min (* -2 7) (* 3 -5)) (max (* -2 -5) (* 3 7))))

(define (div-interval x y)
  (let ((ly (lower-bound y))
        (uy (upper-bound y)))
    (cond ((or (= ly 0) (= uy 0))
           (error "divident spans zero " y))
          ((eq? (> ly 0) (> uy 0))
           (mul-interval x
                         (make-interval (/ 1.0 uy)
                                        (/ 1.0 ly))))
          (else
            (error "divident spans zero " y)))))

(define (add-interval x y)
  (make-interval (+ (lower-bound x) (lower-bound y))
                 (+ (upper-bound x) (upper-bound y))))

(define (minus-interval x)
  (make-interval (- (upper-bound x)) (- (lower-bound x))))

(define (sub-interval x y)
  (make-interval (- (lower-bound x) (upper-bound y))
                 (- (upper-bound x) (lower-bound y))))

;; width of an interval is half of the difference between its upper and lower
;; bounds
;; (width (add-interval x y)) = (+ (width x) (width y))
;; (width x) = (width -x)
;; (width (sub-interval x y)) = (width (add-interval x -y))
;;                            = (+ (width x) (width -y))
;;                            = (+ (width x) (width y))
(define (width x)
  (/ (- (upper-bound x) (lower-bound x)) 2.0))

(define (make-center-width c w)
  (make-interval (- c w) (+ c w)))
(define (center i)
  (/ (+ (lower-bound i) (upper-bound i)) 2))
(define (width i)
  (/ (- (upper-bound i) (lower-bound i)) 2))

(define (make-center-percent c p)
  (let ((w (* c p)))
    (make-center-width c w)))
(define (percent i)
  (/ (width i) (center i)))

;; (2 6) (c1-w1 c1+w1)
;; (6 10) (c2-w2 c2+w2)
;; (12 60) ((c1c2 + w1w2 - c1w2 - c2w1) (c1c2+w1w2+c1w2+c2w1))
;; (c1w2 + c2w1) / (c1c2 + w1w2)
;; (c1/w1 + c2/w2) / (c1c2/w1w2 + 1)
;; (p1 + p2) / (p1p2 + 1)
(define i (make-center-percent 2 1e-36))
(define j (make-center-percent 5 1e-36))
(eq? #t (let ((pi (percent i))
              (pj (percent j)))
          (= (percent (mul-interval i j))
             (/ (+ pi pj) (+ (* pi pj) 1)))))

(define (par1 r1 r2)
  (div-interval (mul-interval r1 r2)
                (add-interval r1 r2)))
(define (par2 r1 r2)
  (let ((one (make-interval 1 1)))
    (div-interval one
                  (add-interval (div-interval one r1)
                                (div-interval one r2)))))

(define r1 (make-center-percent 3 .5))
(define r2 (make-center-percent 5 .5))
(display (par1 r1 r2))
(display " *** ")
(display (par2 r1 r2))
(display " *** ")
(display (equal? (par1 r1 r2) (par2 r1 r2)))
(newline)

(define r3 (make-center-percent 3 1e-36))
(define r4 (make-center-percent 5 1e-36))
(display (par1 r3 r4))
(display " *** ")
(display (par2 r3 r4))
(display " *** ")
(display (equal? (par1 r3 r4) (par2 r3 r4)))
(newline)
